	ACTIVE_PROFILE = dev
	
	AUDITABLE_ADMIN_USER = 1
	
	HEADER_USERID = userid
	
	CREATE_RECORD_SUCESS =  Created Successfully
	
	UPDATE_RECORD_SUCESS =  Updated Successfully
	
	DELETE_RECORD_SUCESS =  Deleted Successfully
	
	FETCH_RECORD_SUCESS =   Fetch Successfully
	
	CREATE_RECORD_FAILED =  Create Failed
	
	UPDATE_RECORD_FAILED =  Update Failed
	
	DELETE_RECORD_FAILED =  Delete Failed
	
	FETCH_RECORD_FAILED =   Fetch Failed
	
	EXCEPTION_OCCURED = Exception Occurred::
	
	SERVER_ERROR = Internal server error
	
	BAD_REQUEST = Request is not valid
	
	HEADER_AUTH = authToken
	
	RES_STATUS_SUCCESS = SUCCESS
	
	RES_STATUS_ERROR = ERROR
	
	ACTIVE =1
	
	IN_ACTIVE=0
	
	ZERO = 0
	
	NPA_REVERSAL_STATUS = 2
	
	NO_PARENT_RECORD = No parent record(s).
	
	ACTIVE_STATUS = Active
	
	IN_ACTIVE_STATUS = In-Active
	 
	NA = N/A
	
    TRUE = true

    FALSE = false
	 
	STATUS = status

	YES = Yes
	
	NO = No
	
	SIGN_URL = /users/check_user_login
	
	FORGET_PWD_URL = /users/forgetpwd
	
	USER_ACCESS_MENU = /users/get_access_menus

	URL=url
	
	SIGN_URL = /users/check_user_login
	
	FORGET_PWD_URL = /users/forgetpwd
	
	USER_ACCESS_MENU = /users/get_access_menus

	URL=url
	
	ACTIVE =1
	
	IN_ACTIVE=0
	
	ACTIVE_STATUS = Active
	
	IN_ACTIVE_STATUS = In-Active
	
	SETTINGS = Settings 
	
	SUCCESS_STATUS = 1
	
	FAIL_STATUS = 0
	
	NAME_PATTERN_FOR_ORGANIZATIONS = ^[^\\\\s][a-zA-Z0-9-_,@.&*#$ /?()\\\\s]*$
	 
	NAME_PATTERN = ^[a-zA-Z][a-zA-Z.\\s]*$
	 
	MOBILE_PATTERN = ^[6-9]{1}[0-9]{9}
	 
	SHORT_CODE_PATTERN = ^[A-Za-z]{4}
	 
	EMAIL_PATTERN = ^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$
	 
	RBI_CODE_PATTERN = ^[A-Za-z0-9]{4}
	 